databases:
  - name: aws_marketplace_project
    databaseName: aws_marketplace_project
    user: aws_marketplace_project
    plan: free

services:
  - type: web
    name: aws_marketplace_project
    plan: free
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn aws_marketplace_project.wsgi:application"
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: aws_marketplace_project
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
