# Generated by Django 3.2.9 on 2021-11-23 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('aws_marketplace_app', '0003_auto_20211123_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('display_image', models.ImageField(upload_to='user_display_image')),
                ('biography', models.CharField(max_length=256)),
                ('gender', models.IntegerField(blank=True, choices=[(None, '(Unknown)'), (1, 'Male'), (2, 'Female'), (3, 'Other')], null=True)),
                ('address', models.CharField(max_length=256)),
                ('postal_code', models.IntegerField()),
                ('mobile_no', models.CharField(max_length=50)),
            ],
        ),
    ]
