# Generated by Django 3.2.9 on 2021-11-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_marketplace_app', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
