# Generated by Django 3.2.9 on 2021-11-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_marketplace_app', '0007_postingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
