# Generated by Django 3.2.9 on 2022-01-13 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aws_marketplace_app', '0009_auto_20211124_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingimage',
            name='image',
            field=models.ImageField(upload_to='uploads/media/posting_image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='display_image',
            field=models.ImageField(upload_to='uploads/media/user_display_image'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_created_by', to=settings.AUTH_USER_MODEL)),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aws_marketplace_app.posting')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(None, '(Unknown)'), (0, 'Pending'), (1, 'Packed'), (2, 'Shipped'), (3, 'Delivered'), (81, 'Cancelled by User'), (82, 'Cancelled by Seller')], default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_created_by', to=settings.AUTH_USER_MODEL)),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aws_marketplace_app.posting')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
