# Generated by Django 3.2.9 on 2022-01-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_marketplace_app', '0010_auto_20220113_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='biography',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='display_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/media/user_display_image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
