# Generated by Django 3.2.9 on 2022-01-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_marketplace_app', '0011_auto_20220114_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='condition',
            field=models.IntegerField(choices=[(None, '(Unknown)'), (1, 'New'), (2, 'Used - Like New'), (3, 'Used - Excellent'), (4, 'Used - Good'), (5, 'Used - Fair'), (6, 'Used - Salvage')], default=1),
        ),
        migrations.AlterField(
            model_name='posting',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='manufacturer',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='model_name',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='postal_code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='posting',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
